//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int Id { get; set; }
        public string NameSurname { get; set; }
        public string PersoEmail { get; set; }
        public string AsanaId { get; set; }
        public string Image { get; set; }
        public string Role { get; set; }
    }
}
